-- USER SQL
CREATE USER "SHOP_DEV" IDENTIFIED BY "s34"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "SHOP_DEV" QUOTA 10M ON "USERS";

-- ROLES
GRANT "CONNECT" TO "SHOP_DEV" ;
GRANT "RESOURCE" TO "SHOP_DEV" ;

-- SYSTEM PRIVILEGES

