SELECT EXTRACT(DAY FROM SYSDATE) 일자, EXTRACT(MONTH FROM SYSDATE) 월, EXTRACT(YEAR FROM SYSDATE) 년도 FROM dual;

SELECT SYSTIMESTAMP A, EXTRACT(DAY FROM SYSTIMESTAMP) B, EXTRACT(HOUR FROM LOCALTIMESTAMP) C FROM dual;
SELECT SYSTIMESTAMP A, EXTRACT(HOUR FROM SYSTIMESTAMP) B, EXTRACT(HOUR FROM LOCALTIMESTAMP) C FROM dual;
SELECT SYSTIMESTAMP A, TO_CHAR(SYSTIMESTAMP, 'HH12') B, EXTRACT(HOUR FROM LOCALTIMESTAMP) C FROM dual;

SELECT SYSTIMESTAMP,
TO_CHAR(SYSTIMESTAMP, 'HH24') ch,
EXTRACT(TIMEZONE_HOUR FROM SYSTIMESTAMP) etzh,
EXTRACT(HOUR FROM SYSTIMESTAMP) eh,
EXTRACT(HOUR FROM CAST(SYSTIMESTAMP AS TIMESTAMP)) ehc
FROM dual;

SELECT SYSTIMESTAMP,
EXTRACT(HOUR FROM SYSTIMESTAMP) h1,
EXTRACT(HOUR FROM SYSTIMESTAMP) + EXTRACT(TIMEZONE_HOUR FROM SYSTIMESTAMP) h2
FROM dual;

SELECT first_name, hire_date, 
EXTRACT(YEAR FROM hire_date) HIRE_YEAR, 
EXTRACT(DAY FROM hire_date) HIRE_DAY 
FROM employees;

SELECT first_name, hire_date, SYSDATE, 
MONTHS_BETWEEN(SYSDATE, hire_date) M_BETWEEN, 
TRUNC(MONTHS_BETWEEN(SYSDATE, hire_date)) T_M_BETWEEN 
FROM employees 
WHERE department_id = 30
ORDER BY M_BETWEEN;

SELECT first_name, hire_date, 
ADD_MONTHS(hire_date, 5) "add_mon" 
FROM employees 
WHERE department_id IN(10, 30) 
ORDER BY hire_date DESC;

SELECT first_name, hire_date,
NEXT_DAY(hire_date, '월요일') "nd_Mon",
NEXT_DAY(hire_date, 6) "nd_Fri"
FROM employees
WHERE department_id = 30
ORDER BY hire_date DESC;