DROP TABLE PRODUCTTBL;
-- memberTbl 생성
DROP TABLE MEMBERTBL;
CREATE TABLE MEMBERTBL 
(
  MEMBERID CHAR(8) NOT NULL 
, MEMBERNAME NCHAR(5) NOT NULL 
, MEMBERADDRESS NVARCHAR2(20) 
, CONSTRAINT MEMBERTBL_PK PRIMARY KEY 
  (
    MEMBERID 
  )
  ENABLE 
);


-- productTbl
CREATE TABLE PRODUCTTBL 
(
  PRODUCTNAME NCHAR(4) NOT NULL 
, PRICE NUMBER(7) NOT NULL 
, MADEDATE DATE 
, COMPANY NCHAR(5) 
, AMOUNT NUMBER(3) NOT NULL 
, CONSTRAINT PRODUCTTABL_PK PRIMARY KEY 
  (
    PRODUCTNAME 
  )
  ENABLE 
);

-- memberTbl에 데이터 입력
INSERT INTO MEMBERTBL (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('KANG', N'강아지', N'서울시 관악구 신림동');
INSERT INTO MEMBERTBL (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('GOYA', N'고양이', N'경기 성남시 분당구');
INSERT INTO MEMBERTBL (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('MANG', N'망아지', N'인천 부평시 부평구');
INSERT INTO MEMBERTBL (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('SONG', N'송아지', N'대전 유성구 도마동');

-- productTbl 데이터 입력
INSERT INTO PRODUCTTBL (PRODUCTNAME, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'컴퓨터', '100', TO_DATE('2023-01-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'삼성', '19');
INSERT INTO PRODUCTTBL (PRODUCTNAME, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'텔레비전', '24', TO_DATE('2021-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'대우', '20');
INSERT INTO PRODUCTTBL (PRODUCTNAME, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'냉장고', '150', TO_DATE('2020-06-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'LG', '150');

-- '텔리비전' 정보 가져오기
SELECT * FROM productTbl WHERE productName = '텔레비전';

-- productTbl 재생성
DROP TABLE PRODUCTTBL;
CREATE TABLE PRODUCTTBL 
(
  IDNUM NUMBER(5) NOT NULL 
, PRODUCTNAME NCHAR(4) NOT NULL 
, MEMBERID CHAR(8) NOT NULL 
, PRICE NUMBER(7) NOT NULL 
, MADEDATE DATE 
, COMPANY NCHAR(5) 
, AMOUNT NUMBER(3) NOT NULL 
, CONSTRAINT PRODUCTTBL_PK PRIMARY KEY 
  (
    PRODUCTNAME 
  )
  ENABLE 
);

-- 시퀀스 설정
DROP SEQUENCE SHOPSEQUENCE;
CREATE SEQUENCE SHOPSEQUENCE INCREMENT BY 10 START WITH 1;

CREATE TRIGGER PRODUCTTBL_TRG 
BEFORE INSERT ON PRODUCTTBL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDNUM IS NULL THEN
      SELECT SHOPSEQUENCE.NEXTVAL INTO :NEW.IDNUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

ALTER TABLE PRODUCTTBL
ADD CONSTRAINT PRODUCTTBL_FK1 FOREIGN KEY
(
  MEMBERID 
)
REFERENCES MEMBERTBL
(
  MEMBERID 
)
ENABLE;

INSERT INTO PRODUCTTBL (PRODUCTNAME, MEMBERID, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'컴퓨터', 'KANG', '100', TO_DATE('2023-02-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'삼성', '19');
INSERT INTO PRODUCTTBL (PRODUCTNAME, MEMBERID, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'텔레비전', 'MANG', '24', TO_DATE('2021-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'대우', '20');
INSERT INTO PRODUCTTBL (PRODUCTNAME, MEMBERID, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'냉장고', 'SONG', '150', TO_DATE('2020-06-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'LG', '8');
INSERT INTO PRODUCTTBL (PRODUCTNAME, MEMBERID, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'노트북', 'GOYA', '10', TO_DATE('2023-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'현대', '1');




