-- USER SQL
ALTER USER "STUDY"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "STUDY" QUOTA 10M ON "USERS";

-- ROLES
GRANT "CONNECT" TO "STUDY" ;
GRANT "RESOURCE" TO "STUDY" ;

-- SYSTEM PRIVILEGES

