-- USER SQL
CREATE USER TABLEDB3411 IDENTIFIED BY "3411"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "DBA" TO TABLEDB3411 ;
GRANT "CONNECT" TO TABLEDB3411 ;
GRANT "RESOURCE" TO TABLEDB3411 ;

-- SYSTEM PRIVILEGES

